import importlib.util
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
spec = importlib.util.spec_from_file_location("forge_ownership", ROOT / ".forge" / "forge.py")
forge = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = forge
spec.loader.exec_module(forge)


class ForgeOwnershipTests(unittest.TestCase):
    def test_canonical_output_has_one_owner(self):
        self.assertEqual(forge.CANONICAL_HOST["output_path"], ".agents/skills/{name}/SKILL.md")
        for host in forge.available_hosts():
            self.assertNotIn("output_path", forge.load_host(host))

    def test_adapter_command_paths_are_unique(self):
        paths = [forge.load_host(h).get("command_path") for h in forge.available_hosts()]
        paths = [p for p in paths if p]
        self.assertEqual(len(paths), len(set(paths)))

    def test_model_profile_cannot_overwrite_canonical_skill(self):
        with self.assertRaises(SystemExit):
            forge.build_one("ops/explain", "portable", "gpt", True)

    def test_project_command_is_not_treated_as_generated(self):
        self.assertFalse(forge.generated_command("Run the Resonance process for my project."))
        self.assertTrue(forge.generated_command("<!-- Generated by Resonance Forge. -->\n---"))


if __name__ == "__main__":
    unittest.main()
